# Generated by Django 4.1a1 on 2022-09-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scaninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=32)),
                ('taskname', models.CharField(max_length=64)),
                ('appname', models.CharField(max_length=64)),
                ('appid', models.CharField(max_length=64)),
                ('starttime', models.CharField(max_length=32)),
                ('endtime', models.CharField(max_length=32)),
                ('Murl', models.CharField(max_length=128)),
                ('Auth_Token', models.CharField(max_length=64)),
                ('cftk', models.CharField(max_length=64)),
                ('regex_str', models.CharField(max_length=516)),
                ('taskbegintime', models.CharField(max_length=32)),
                ('finishtime', models.CharField(max_length=32)),
                ('progress', models.CharField(max_length=16)),
                ('report', models.CharField(max_length=128)),
            ],
        ),
    ]
